### ISSUE TITLE
Node SHDLC Driver

### ISSUE THREAD

**Issue by hpgmiskin** [Sensirion/python-shdlc-driver#1]
I work at a company which uses Node to communicate with Teensy devices over serial. We are looking to add the ability to communicate with a SF06 flow sensor using the RS485 sensor cable. Currently we have implemented a test script using the the Python SHDLC driver and the RS485 SF06 implementation guide.

We would like to create a basic Node package which uses [Node SerialPort · Node.js package to access serial ports for Linux, OSX and Windows.](https://serialport.io/) in order to communicate with Sensirion devices using SHDLC. Given our use case is to control the SF06 flow sensor I would likely include sensor specific commands in the library.

There is some existing work on a High-level data link control Node module called [elkrem/HDLC](https://github.com/elkrem/HDLC). We would intend to use this for reference, however, largely write from the ground up using Typescript.

Are there any licensing issues which we should be aware of when writing this library? Our current plan is to release this as an open source package under [Cytera](https://github.com/cytera), then at a future point we could transfer ownership or the Sensirion team could fork the project. 

Do the Sensirion team have any requests on implementation or approach? We were considering making the serialport library pluggable such that consumers of the package would be able to provide their own.

**Comment by abrauchli** [comment]
Hi @hpgmiskin thanks for your interest in Sensirion products. Sounds like a great projects. As to the external projects, I cannot give any licensing recommendations. If you write your own code you should not run into issues with Sensirion licenses even if you copy the commands from our datasheet or drivers, most of our publications are BSD-3 licensed anyway which gives a lot of room. Since this issue is not related to the python shdlc driver, I'll move ahead and close the issue.

**Comment by hpgmiskin** [comment]
Thanks for your response @abrauchli, I will start work on the project. Is there a more suitable channel of communication to share the package when finished?

**Comment by winkj** [comment]
@hpgmiskin we have a list of drivers here: https://github.com/Sensirion/info, I'd be happy to add your library there as well. Also, if you are building any public demos, it would be great if you could share that with me (jwi at sensirion dot com)!
